spring.application.name=Example
server.port=3002
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=prakash123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat